apiVersion: v1
kind: Pod
metadata:
  name: result-app-pod
  labels:
    name: result-app-pod
    app: voting-app
spec:
  containers:
  - name: result-app
    image: dhanvantarisoftware/result-image
    ports:
     - containerPort: 80
