apiVersion: v1
kind: Pod
metadata:
  name: voting-app-pod
  labels:
    app: voting-app
spec:
  containers:
  - name: voting-app-container
    image: dhanvantarisoftware/votingapplication
    ports:
         - containerPort: 80