apiVersion: v1
kind: Pod
metadata:
  name: worker-app-pod
  labels:
    name: worker-app-pod
    app: voting-app
spec:
  containers:
  - name: worker-app
    image: dhanvantarisoftware/workerapp-image